extends Node

const MIN = "MIN"
const GRAB_COFFEE = "GRAB COFFEE"
const HELP = "HELP"
const EXPLAIN = "EXPLAIN"
const BACKSTORY = "BACKSTORY"
const LIST_TERMS = "LIST TERMS"
const CHECK_CAPACITY = "CHECK CAPACITY"
const CREATE_FIREWALL = "CREATE FIREWALL"
const LISTEN_REQUESTS = "LISTEN REQUESTS"
const ENABLE_IDS = "ENABLE IDS"
const CHECK_IDS = "CHECK IDS"
const TOGGLE_HARDMODE = "TOGGLE HARDMODE"
const CHECK_EXPLOITS = "CHECK EXPLOITS"
const CLEAR = "CLEAR"

const COMMANDS = [MIN, GRAB_COFFEE, HELP, EXPLAIN, BACKSTORY, LIST_TERMS, CHECK_CAPACITY, CREATE_FIREWALL, LISTEN_REQUESTS, ENABLE_IDS, CHECK_IDS, TOGGLE_HARDMODE, CHECK_EXPLOITS, CLEAR]
