extends Node

const MIN = "MIN"
const GRAB_COFFEE = "GRAB COFFEE"
const HELP = "HELP"
const EXPLAIN = "EXPLAIN"
const BACKSTORY = "BACKSTORY"
const LIST_TERMS = "LIST TERMS"
const CAPACITY = "CAPACITY"
const CREATE_FIREWALL = "CREATE FIREWALL"
const LISTEN_REQUESTS = "LISTEN REQUESTS"
const ENABLE_IDS = "ENABLE IDS"
const CHECK_IDS = "CHECK IDS"
const TOGGLE_HARDMODE = "TOGGLE HARDMODE"

const COMMANDS = [MIN, GRAB_COFFEE, HELP, EXPLAIN, BACKSTORY, LIST_TERMS, CAPACITY, CREATE_FIREWALL, LISTEN_REQUESTS, ENABLE_IDS, CHECK_IDS, TOGGLE_HARDMODE]
